### ISSUE TITLE
problem with marvin query

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#101]
using marvin 2.0.8 I tried 

spax_search = 'nsa.logmass < 9.5 and emline_sew_ha_6564 > 30'

q4 = Query(searchfilter=spax_search, returnparams=['emline_gflux_ha_6564', 'emline_gflux_hb_4862', 'stellar_vel'])
r4 = q4.run()

I get the following error message

INFO: No release version set. Setting default to MPL-5
WARNING: path
         /Users/Francesco/sas/mangawork/manga/spectro/redux/v2_0_1/drpall-v2_0_1
         .fits cannot be found. Setting drpall to None.
WARNING: No local database found. Setting mode to remote
Your parsed filter is: 
and_(nsa.logmass<9.5, emline_sew_ha_6564>30)
Traceback (most recent call last):

  File "<ipython-input-1-2990b29f4e09>", line 1, in <module>
    runfile('/Users/Francesco/Desktop/query.py', wdir='/Users/Francesco/Desktop')

  File "/Applications/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/Applications/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/Users/Francesco/Desktop/query.py", line 19, in <module>
    r4 = q4.run()

  File "/Applications/anaconda/lib/python2.7/site-packages/marvin/tools/query/query.py", line 90, in wrapper
    return f(self, *args, **kwargs)

  File "/Applications/anaconda/lib/python2.7/site-packages/marvin/tools/query/query.py", line 102, in wrapper
    return f(self, *args, **kwargs)

  File "/Applications/anaconda/lib/python2.7/site-packages/marvin/tools/query/query.py", line 78, in wrapper
    return f(self, *args, **kwargs)

  File "/Applications/anaconda/lib/python2.7/site-packages/marvin/tools/query/query.py", line 750, in run
    print('query remote fail', config._traceback)

AttributeError: 'MarvinConfig' object has no attribute '_traceback'

**Comment by havok2063** [comment]
Dammit.  That's a leftover test print statement I forgot to remove.  I'll have to take it out and push a new release.

**Comment by havok2063** [comment]
This is fixed and will be pushed soon into a new release.
