### ISSUE TITLE
Fix this José! - BinTest errors when nose2 run in py3.5 and marvin server in 3.5

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#136]
======================================================================
ERROR: test_init_from_files (test_bin.TestBinInit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Brian/Work/github_projects/Marvin/python/marvin/tests/tools/test_bin.py", line 83, in test_init_from_files
    modelcube_filename=self.modelcube_filename)
  File "/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/bin.py", line 77, in __init__
    self._load_spaxels(**kwargs)
  File "/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/bin.py", line 124, in _load_spaxels
    raise MarvinError('there are no spaxels associated with binid={0}.'.format(self.binid))
marvin.core.exceptions.MarvinError: there are no spaxels associated with binid=100.

**Comment by havok2063** [comment]
These tests pass when tests are run in 2.7

**Comment by albireox** [comment]
This was a problem with PY3 using generators instead of lists. Fixed in d88357ddd9bb1bef59cba21e2bb22936101ccde4.
