### ISSUE TITLE
Result object representation error with 0 query results

### ISSUE THREAD

**Issue by kbwestfall** [sdss/marvin#242]
```
from marvin.tools.query import Query
q = Query(searchfilter='nsa.z < 0.01')
q.run()
```

Returns:

```
Results contain of a total of 0, only returning the first 0 results
list index out of range
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/raven-5.32.0-py3.5.egg/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/Users/westfall/Work/MaNGA/marvin/python/marvin/tools/query/results.py", line 148, in __repr__
    return ('Marvin Results(results={0}, \nquery={1}, \ncount={2}, \nmode={3}'.format(self.results[0], repr(self.query), self.count, self.mode))
IndexError: list index out of range
list index out of range
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/raven-5.32.0-py3.5.egg/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/Users/westfall/Work/MaNGA/marvin/python/marvin/tools/query/results.py", line 148, in __repr__
    return ('Marvin Results(results={0}, \nquery={1}, \ncount={2}, \nmode={3}'.format(self.results[0], repr(self.query), self.count, self.mode))
IndexError: list index out of range
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/westfall/Work/MaNGA/marvin/python/marvin/tools/query/results.py", line 148, in __repr__
    return ('Marvin Results(results={0}, \nquery={1}, \ncount={2}, \nmode={3}'.format(self.results[0], repr(self.query), self.count, self.mode))
IndexError: list index out of range
```

Should test for > 0 results and report that instead of raising IndexError

**Comment by albireox** [comment]
Fixed as of 2.1.4.
