### ISSUE TITLE
problem with marvin update

### ISSUE THREAD

**Issue by francbelf** [sdss/marvin#262]
I tried pip install --upgrade sdss-marvin

and I get an error. Below the final part of the install and the traceback report. It seems to be related to the appdirs package. I hope it's not due to my own machine though.

Installing collected packages: appdirs, pyparsing, packaging, setuptools, sphinx-bootstrap-theme, Werkzeug, MarkupSafe, Jinja2, Flask, pytz, python-dateutil, matplotlib, blinker, pandas, dogpile.cache, PyYAML, requests, backports.shutil-get-terminal-size, scandir, pathlib2, pickleshare, decorator, wcwidth, prompt-toolkit, ptyprocess, pexpect, pygments, ipython-genutils, enum34, traitlets, ipython, webargs, Pillow, SQLAlchemy, sdss-marvin, coverage, futures, imagesize, babel, sphinxcontrib-websupport, alabaster, docutils, typing, Sphinx, aniso8601
  Found existing installation: appdirs 1.4.0
    Uninstalling appdirs-1.4.0:
      Successfully uninstalled appdirs-1.4.0
  Rolling back uninstall of appdirs
Exception:
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/dist.py", line 270, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 713, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2550, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2280, in parse_map
    for group, lines in data:
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2851, in split_sections
    for line in yield_lines(s):
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2147, in yield_lines
    for ss in strs:
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2475, in _get_metadata
    if self.has_metadata(name):
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1443, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1804, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1684, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1624, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Applications/anaconda/lib/python2.7/site-packages/appdirs-1.4.0-py2.7.egg'Installing collected packages: appdirs, pyparsing, packaging, setuptools, sphinx-bootstrap-theme, Werkzeug, MarkupSafe, Jinja2, Flask, pytz, python-dateutil, matplotlib, blinker, pandas, dogpile.cache, PyYAML, requests, backports.shutil-get-terminal-size, scandir, pathlib2, pickleshare, decorator, wcwidth, prompt-toolkit, ptyprocess, pexpect, pygments, ipython-genutils, enum34, traitlets, ipython, webargs, Pillow, SQLAlchemy, sdss-marvin, coverage, futures, imagesize, babel, sphinxcontrib-websupport, alabaster, docutils, typing, Sphinx, aniso8601
  Found existing installation: appdirs 1.4.0
    Uninstalling appdirs-1.4.0:
      Successfully uninstalled appdirs-1.4.0
  Rolling back uninstall of appdirs
Exception:
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/Applications/anaconda/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/dist.py", line 270, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 713, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2550, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2280, in parse_map
    for group, lines in data:
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2851, in split_sections
    for line in yield_lines(s):
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2147, in yield_lines
    for ss in strs:
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2475, in _get_metadata
    if self.has_metadata(name):
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1443, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1804, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1684, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Applications/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1624, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Applications/anaconda/lib/python2.7/site-packages/appdirs-1.4.0-py2.7.egg'

**Comment by francbelf** [comment]
I next tried 

pip install --upgrade --upgrade-strategy only-if-needed sdss-marvin

which worked

**Comment by albireox** [comment]
We haven't been able to reproduce this and it does not seem to be a frequent problem. It may be related to the order in which the multiple packages that needed to be upgraded were installed. In those cases, manually upgrading the conflicting package and then doing `pip install -U sdss-marvin` usually solves the issue. Closing.
