### ISSUE TITLE
Error when updating Marvin (Anaconda on OSX 10.11.6 (El Capitan))

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#304]
I copy here the mail I have received from Amelia Fraser-McKelvie, University of Nottingham

This morning I upgraded Mavin using the instructions below and I got an error, which I copy below. When running a script, this resulted in the error about Python not being installed as a framework. Now I’m not positive what the actual problem is here, but after a bit of googling I tried 
conda install python.app 
which seemed to fix things. I’m using Anaconda on OSX 10.11.6 (El Capitan). Just thought you’d like to know. I’ll let you know if I run into any more problems which the package upgrade.

 Traceback (most recent call last):
  File "/Users/ppzaf/anaconda/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/ppzaf/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Users/ppzaf/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg'

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

**Comment by albireox** [comment]
This is a known problem of Anaconda, so not really a Marvin issue. I'm not an Anaconda user so somebody else may have better answers but the solutions are either to install the python.app cond package as

`conda install python.app`

or change the Matplotlib backend you are using so that it doesn't need the framework. See [this](https://matplotlib.org/faq/osx_framework.html#conda) for more details.

**Comment by havok2063** [comment]
You can also take a look at this entry in the FAQ.   http://sdss-marvin.readthedocs.io/en/stable/faq.html#matplotlib-backend-problems

**Comment by albireox** [comment]
I think that solves the problem. Closing.
