### ISSUE TITLE
Install Marvin in conda envrionment

### ISSUE THREAD

**Issue by YiqingLiu** [sdss/marvin#318]
Hello, 

I am using anaconda (Python 3) and hope to install sdss-marvin.  

I tried 'conda install sdss-marvin' but got: 
PackageNotFoundError: Package missing in current osx-64 channels: 
  -- sdss-marvin 

Could you please help? Thanks.

**Comment by havok2063** [comment]
Hi Yiqing,

Try `pip install sdss-marvin`.  We recommend using `pip` to install and/or upgrade the Marvin package.  Let us know if you have any troubles.  

Cheers, Brian

**Comment by YiqingLiu** [comment]
Thanks, Brian.  

Unfortunately, in terminal my pip can be only used for Python 2.7, while I hope to use Python 3. 

I tried to run pip in my conda environment and Marvin was installed successfully.  However, I got these when importing it: (I am working in PyCharm.) 
import marvin
INFO: No release version set. Setting default to MPL-5
WARNING: path
         /Users/yiqingliu/sas/mangawork/manga/spectro/redux/v2_0_1/drpall-v2_0_1
         .fits cannot be found. Setting drpall to None.
Backend MacOSX is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-c829bc588ff7>", line 1, in <module>
    import marvin
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/__init__.py", line 477, in <module>
    from marvin.api.api import Interaction
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/api/__init__.py", line 10, in <module>
    from marvin.tools.maps import _get_bintemps
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/maps.py", line 27, in <module>
    import marvin.tools.cube
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/cube.py", line 19, in <module>
    import marvin.tools.spaxel
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/spaxel.py", line 31, in <module>
    from marvin.tools.analysis_props import AnalysisProperty, DictOfProperties
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/analysis_props.py", line 19, in <module>
    class DictOfProperties(marvin.core.core.DotableCaseInsensitive):
AttributeError: module 'marvin' has no attribute 'core'

**Comment by margudo** [comment]
Hello, 

I had the same problem as you. I have OSX and anaconda. The system python version is python 2.7 and I have python3 in anaconda. So to activate pip for python3 try this before pip:

`source activate python3`

You can test which pip is using typing:

`which pip`

Is it is the path to python3 then you can do:

`pip install sdss-marvin`

Every time I need to use python3 I have to type `source activate python3`, to deactivate the virtual environment just type `source deactivate python3`.

I hope this help.
Cheers,
Maria

**Comment by havok2063** [comment]
If you set up a fresh Conda initially with Python 3, then `pip` should map to Python 3 automatically.  If you installed Python 3 separately, you may have to use `pip3` to install python products.  Did you create a separate conda virtual environment with Python 3?  If so, you need to be inside that environment when using `pip`.

**Comment by YiqingLiu** [comment]
Thank both of you so much, Maria and Brian! 

I installed marvin in conda environment using pip3.  It is successful but it warns me as: 
WARNING: path
         /Users/yiqingliu/sas/mangawork/manga/spectro/redux/v2_0_1/drpall-v2_0_1
         .fits cannot be found. Setting drpall to None. 

Should I set something for path?

**Comment by havok2063** [comment]
That warning is just there to say that you do not have the `drpall` file for MPL-5 in the expected location.  It is a normal warning.  You can ignore it and use Marvin as normal.  If you would like Marvin to use the `drpall` file, then you should place that file in that location.  At that point the warning should disappear.

**Comment by YiqingLiu** [comment]
Thanks, Brian.  Now it seems working well.

**Comment by havok2063** [comment]
Great!
