### ISSUE TITLE
Can't access to rss datacubes

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#329]
> crss = RSS(mangaid=galaxy[10])

INFO: No release version set. Setting default to MPL-6
WARNING: local mode failed. Trying remote now.
Traceback (most recent call last):
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 97, in _checkResponse
    isbad = response.raise_for_status()
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.sdss.org/marvin2/api/rss/8255-12705/fibers/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 17, in <module>
    crss = RSS(mangaid=galaxy[10])
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/tools/rss.py", line 91, in __init__
    _fibers = self._init_fibers()
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/tools/rss.py", line 209, in _init_fibers
    response = self._toolInteraction(url)
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/core.py", line 347, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 46, in __init__
    self._sendRequest(request_type)
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 176, in _sendRequest
    self._checkResponse(self._response)
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 120, in _checkResponse
    raise BrainError('Requests Http Status Error: {0}\n{1}'.format(http, errmsg))
brain.core.exceptions.BrainError: Requests Http Status Error: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.sdss.org/marvin2/api/rss/8255-12705/fibers/
None
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 137, in wrapper
    return wrapped(*args, **kwargs)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 109, in wrapper
    returnVal = f(*args, **kwargs)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classy-0.6.10-py2.7.egg/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
   File "/home/manga/software/git/manga/marvin/2.2.1/python/marvin/api/__init__.py", line 366, in wrapper
    return newfunc(*args, **kwargs)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/webargs-1.5.3-py2.7.egg/webargs/core.py", line 443, in wrapper
    return func(*new_args, **kwargs)
   File "/home/manga/software/git/manga/marvin/2.2.1/python/marvin/api/rss.py", line 180, in getAllFibers
    self.results['data']['wavelength'] = rss[0].wavelength.tolist()
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/astropy-1.3-py2.7-linux-x86_64.egg/astropy/units/quantity.py", line 1255, in tolist
    raise NotImplementedError("cannot make a list of Quantities.  Get "

Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

**Comment by havok2063** [comment]
Can you provide a bit more information on the steps taken here?  Which galaxy is `galaxy[10]` and which `release`?

**Comment by margudo** [comment]
It's a MPL6 galaxy. 

But it's weird, the first time I tries to reproduce the error:

```
from marvin.tools.rss import RSS
crss = RSS(mangaid='1-255958') 
```
I'm getting 

```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/core.py", line 436, in __del__
    if self.data_origin == 'file' and isinstance(self.data, astropy.io.fits.HDUList):
AttributeError: 'RSS' object has no attribute 'data_origin'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/core.py", line 436, in __del__
    if self.data_origin == 'file' and isinstance(self.data, astropy.io.fits.HDUList):
AttributeError: 'RSS' object has no attribute 'data_origin'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/core/core.py", line 436, in __del__
    if self.data_origin == 'file' and isinstance(self.data, astropy.io.fits.HDUList):
AttributeError: 'RSS' object has no attribute 'data_origin'
```

I tried a second time and it's working

```
In [16]: crss = RSS(mangaid='1-255958')
    ...: 

In [17]: crss
Out[17]: <Marvin RSS (mangaid='1-255958', plateifu='8255-12705', mode='local', data_origin='file')>

In [18]: 
```

**Comment by margudo** [comment]
It's also working this way:

```
In [22]: crss = RSS(mangaid=galaxy[10])
    ...: 

In [23]: crss
Out[23]: <Marvin RSS (mangaid='1-255958', plateifu='8255-12705', mode='local', data_origin='file')>

```

**Comment by margudo** [comment]
Now I want to download the rss file, so I do:

```
In [26]: crss.download
Out[26]: <bound method RSS.download of <Marvin RSS (mangaid='1-255958', plateifu='8255-12705', mode='local', data_origin='file')>>
```
How do I know if it is doing something?
Is it going to be downloaded in my SAS? I mean

```
In [27]: import os
    ...: print(os.environ['SAS_BASE_DIR'])
    ...: 
/home/mamen/Work/manga/spectro/redux/v2_3_1
```

BTW, in the documentation, there is no link to rss in the list of tools from the main page, you have to go to the Marvin Tools Reference page: 
http://sdss-marvin.readthedocs.io/en/stable/api/tools.html?highlight=rss#

It would be nice to have them in the same order in both pages.

Cheers, Maria

**Comment by havok2063** [comment]
Did you have this file originally, before the first time you tried to use `RSS`?  From the second time, it looks like you already have the file.  

```
In [23]: crss
Out[23]: <Marvin RSS (mangaid='1-255958', plateifu='8255-12705', mode='local', data_origin='file')>
```
The `mode` is local and the `data_origin` is file, so it seems you already have the file, so that might be why it worked the second time.  And you don't need to download it.  The `download` is a method, so you have to call it like `crss.download()`.  Anytime you see `<bound method ...>`, that means it's a method and have to call it with parantheses.  Can you try using `RSS` again with a galaxy that you do not have on your laptop and see what happens?

**Comment by margudo** [comment]
Hi,

I didn't have the file the first time I tried. Yes, the second time I already had it.
I'm trying in another computer now, where I don't have any MaNGA data, and it's failing but with other error message this time:

 (python3) Marias-MacBook-Pro:~ maria$ pythonw
Python 3.6.0 |Anaconda 4.3.1 (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from marvin.tools.rss import RSS
[WARNING]: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
INFO: No release version set. Setting default to MPL-6
[WARNING]: MarvinUserWarning: path /Users/maria/sas/mangawork/manga/spectro/redux/v2_3_1/drpall-v2_3_1.fits cannot be found. Setting drpall to None.
>>> crss = RSS(mangaid='1-255958')
[WARNING]: MarvinUserWarning: local mode failed. Trying remote now.
Traceback (most recent call last):
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 136, in _checkResponse
    isbad = response.raise_for_status()
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.sdss.org/marvin2/api/rss/8255-12705/fibers/

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/tools/rss.py", line 91, in __init__
    _fibers = self._init_fibers()
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/tools/rss.py", line 209, in _init_fibers
    response = self._toolInteraction(url)
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/core/core.py", line 347, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 51, in __init__
    self._sendRequest(request_type)
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 218, in _sendRequest
    self._checkResponse(self._response)
  File "/Users/maria/anaconda/envs/python3/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 159, in _checkResponse
    raise BrainError('Requests Http Status Error: {0}\n{1}'.format(http, errmsg))
brain.core.exceptions.BrainError: Requests Http Status Error: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.sdss.org/marvin2/api/rss/8255-12705/fibers/
None
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 137, in wrapper
    return wrapped(*args, **kwargs)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 109, in wrapper
    returnVal = f(*args, **kwargs)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classful-0.14.1-py2.7.egg/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classful-0.14.1-py2.7.egg/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
   File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/api/__init__.py", line 369, in wrapper
    return newfunc(*args, **kwargs)
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/webargs-1.5.3-py2.7.egg/webargs/core.py", line 443, in wrapper
    return func(*new_args, **kwargs)
   File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/api/rss.py", line 180, in getAllFibers
    self.results['data']['wavelength'] = rss[0].wavelength.tolist()
   File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/astropy-1.3-py2.7-linux-x86_64.egg/astropy/units/quantity.py", line 1255, in tolist
    raise NotImplementedError("cannot make a list of Quantities.  Get "
>>> 
```

**Comment by havok2063** [comment]
Ok, thanks.  I'll take a look and get back to you.

**Comment by havok2063** [comment]
There was a bug now that wavelength is a `Quantity` and `Quantities` cannot be converted to lists.  I have fixed this.  This is the same as your original error I'm going to close this.
