### ISSUE TITLE
too many arrow clicks on query postage stamp page crash

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#346]
Dave
Web - Query - View Galaxies page
If you click "view galaxies" after running a search, then hit the "previous" or "next" buttons too many times, it crashes

Dave - Query/postage stamp
- go to ​https://sas.sdss.org/marvin2/search/
- type haflux > 1000 in "Input Search Filter"
- click "search"
- click "view galaxies"
- click "previous" OR click "next" until you reach the end of the list, then click "next" again --> -
 Crash

**Comment by havok2063** [comment]
traceback 1 when hit the last arrow button

```
WARNING: Client.get_ident is deprecated. The event ID is now returned as the result of
         capture.
[2018-02-26 11:28:00,227] ERROR in app: Exception on /marvin2/search/postage/14/ [GET]
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 137, in wrapper
    return wrapped(*args, **kwargs)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 109, in wrapper
    returnVal = f(*args, **kwargs)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classful-0.14.1-py2.7.egg/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classful-0.14.1-py2.7.egg/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/web/controllers/search.py", line 233, in postagestamp
    imfiles = getImagesByList(plateifus, as_url=True, mode='local', release=self._release)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/utils/general/images.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/utils/general/images.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/utils/general/images.py", line 301, in getImagesByList
    idtype = parseIdentifier(inputlist[0])
IndexError: list index out of range
ERROR: Exception on /marvin2/search/postage/14/ [GET]
```

traceback 2 when hitting `next` button multiple times fast
```

WARNING: Client.get_ident is deprecated. The event ID is now returned as the result of
         capture.
[2018-02-26 11:28:14,281] ERROR in app: Exception on /marvin2/search/postage/5/ [GET]
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 137, in wrapper
    return wrapped(*args, **kwargs)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/flask_profiler-1.5-py2.7.egg/flask_profiler/flask_profiler.py", line 109, in wrapper
    returnVal = f(*args, **kwargs)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classful-0.14.1-py2.7.egg/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/site-packages/Flask_Classful-0.14.1-py2.7.egg/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/web/controllers/search.py", line 233, in postagestamp
    imfiles = getImagesByList(plateifus, as_url=True, mode='local', release=self._release)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/utils/general/images.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/utils/general/images.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/manga/software/git/manga/marvin/2.2.2/python/marvin/utils/general/images.py", line 301, in getImagesByList
    idtype = parseIdentifier(inputlist[0])
IndexError: list index out of range
ERROR: Exception on /marvin2/search/postage/5/ [GET]
```

**Comment by havok2063** [comment]
Using `2.2.2` I can no longer recreate this error in either Firefox or Chrome

**Comment by havok2063** [comment]
Closing this until we reexperience it.
