### ISSUE TITLE
downloading cube in global mode fails

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#359]
Mark
Tools - Cube
When downloading a cube with MPL-4/5/6 using config.download = True and specifying by MaNGA-ID, the download fails, see error below

Mark - Download cube using MaNGA-ID
- config.setRelease('MPL-4'). # same with MPL-5 and MPL-6
- config.mode = 'local'
- config.download = True
- cc = Cube(mangaid='12-193481')
- WARNING: subprocess 1397 is still running, '_File' object has no attribute '_file' Traceback (most - recent call last): File "[Anaconda]/raven/utils/serializer/manager.py", line 76, in transform return -
 repr(value), File "[Anaconda]/astropy/io/fits/file.py", line 219, in repr self._file), AttributeError?: -
 '_File' object has no attribute '_file'

Mark - Download cube using Plate-IFU
- config.setRelease('MPL-4'). # same with MPL-5 and MPL-6
- config.mode = 'local'
- config.download = True
- cc = Cube(plateifu='8485-1903')
- sdss_access.path.path.AccessError?: Return code 23, b'rsync: link_stat -
 "mangawork/manga/spectro/redux/v1_5_1/8485/stack/manga-8485-1903-LOGCUBE.fits.gz" (in -
 sas) failed: No such file or directory (2)\nrsync error: some files could not be transferred (code - 23) at /BuildRoot/Library/Caches?/com.apple.xbs/Sources/rsync/rsync-52/rsync/main.c(1404) -
 [receiver=2.6.9]\n'

**Comment by havok2063** [comment]
I could not recreate the above with MPL-6.  Attempting with MPL-4, I cannot recreate the error using the manga-id identifier.   Attempting the plateifu identifier produces the following traceback, which is different than the above.  I believe in this case 8485-1903 does not exist.  
```

config.setRelease('MPL-4')
cc = Cube(plateifu='8485-1903')
---------------------------------------------------------------------------
AccessError                               Traceback (most recent call last)
<ipython-input-9-71f53b1a0337> in <module>()
----> 1 cc = Cube(plateifu='8485-1903')

/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/spaxel.pyc in spaxel_factory(cls, *args, **kwargs)
     70
     71     if cls is not SpaxelBase:
---> 72         return type.__call__(cls, *args, **kwargs)
     73
     74     cube = kwargs.pop('cube', None)

/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/cube.pyc in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download, nsa_source)
     79         MarvinToolsClass.__init__(self, input=input, filename=filename, mangaid=mangaid,
     80                                   plateifu=plateifu, mode=mode, data=data, release=release,
---> 81                                   drpall=drpall, download=download)
     82
     83         NSAMixIn.__init__(self, nsa_source=nsa_source)

/Users/Brian/Work/github_projects/Marvin/python/marvin/core/core.pyc in __init__(self, input, filename, mangaid, plateifu, mode, data, release, drpall, download)
    152
    153         if self.mode == 'local':
--> 154             self._doLocal()
    155         elif self.mode == 'remote':
    156             self._doRemote()

/Users/Brian/Work/github_projects/Marvin/python/marvin/core/core.pyc in _doLocal(self)
    283                 else:
    284                     if self._forcedownload:
--> 285                         self.download()
    286                         self.data_origin = 'file'
    287                     else:

/Users/Brian/Work/github_projects/Marvin/python/marvin/tools/cube.pyc in download(self)
    125
    126         return super(Cube, self).download('mangacube', ifu=ifu,
--> 127                                           drpver=self._drpver, plate=plate)
    128
    129     def __repr__(self):

/Users/Brian/Work/github_projects/Marvin/python/marvin/core/core.pyc in download(self, pathType, **pathParams)
    313             rsync_access.remote()
    314             rsync_access.add(pathType, **pathParams)
--> 315             rsync_access.set_stream()
    316             rsync_access.commit()
    317             paths = rsync_access.get_paths()

/Users/Brian/Work/sdss/repo/sdss/sdss_access/trunk/python/sdss_access/sync/rsync.pyc in set_stream(self)
     59             self.stream.cli.env = {'RSYNC_PASSWORD':self.auth.password} if self.auth.ready() else None
     60             if self.stream.source and self.stream.destination:
---> 61                 for task in self.initial_stream.task: self.set_stream_task(task)
     62
     63     def get_task_out(self,task=None):

/Users/Brian/Work/sdss/repo/sdss/sdss_access/trunk/python/sdss_access/sync/rsync.pyc in set_stream_task(self, task)
     86
     87     def set_stream_task(self,task=None):
---> 88         out = self.get_task_out(task=task)
     89         stream_has_task = False
     90         for location,source,destination in self.generate_stream_task(task=task,out=out):

/Users/Brian/Work/sdss/repo/sdss/sdss_access/trunk/python/sdss_access/sync/rsync.pyc in get_task_out(self, task)
     66             if self.verbose: print("rsync -R %(source)s" % task)
     67             status, out, err = self.stream.cli.foreground_run(command)
---> 68             if status: raise AccessError("Return code %r\n%s" % (status,err))
     69         else: out = None
     70         return out

AccessError: Return code 23
rsync: link_stat "mangawork/manga/spectro/redux/v1_5_1/8485/stack/manga-8485-1903-LOGCUBE.fits.gz" (in sas) failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(1400) [receiver=2.6.9]

```

**Comment by havok2063** [comment]
No one else can reproduce.  Closing until further notice.
