### ISSUE TITLE
import error after 2.2.2 upgrade

### ISSUE THREAD

**Issue by margudo** [sdss/marvin#377]
>>> import marvin
[WARNING]: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
INFO: No release version set. Setting default to MPL-6
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/__init__.py", line 478, in <module>
    from marvin.api.api import Interaction
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/api/api.py", line 15, in <module>
    from brain.api.api import BrainInteraction
  File "/home/mamen/anaconda3/lib/python3.5/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 5, in <module>
    import msgpack
ImportError: No module named 'msgpack'

**Comment by havok2063** [comment]
Yeah, I was in the middle of doing stuff in the Brain when I had to push this patch.  Right now the solution is just to install it.  `pip install msgpack` and to do the same for any other package Marvin wants.

**Comment by margudo** [comment]
Fixed with pip install msgpack_numpy
