### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#396]
Error when attempting to convert 300 query results into Marvin Maps.  

```
$ q, r = doQuery(searchfilter='nsa.sersic_logmass >= 10 and nsa.sersic_logmass <= 11', limit=300)

Your parsed filter is: 
and_(nsa.sersic_logmass>=10, nsa.sersic_logmass<=11)
Results contain of a total of 2037. Only returning the first 300 results.

$ df = r.toDF()

$ r.convertToTool('maps', mode='auto')

Converting results to Marvin Maps objects

ERROR:root:Internal Python error in the inspect module.
```
Below is the traceback from this internal error.

```
Traceback (most recent call last):
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/inspect.py", line 1051, in getinnerframes
    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/inspect.py", line 1011, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/inspect.py", line 453, in getsourcefile
    if hasattr(getmodule(object, filename), '__loader__'):
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/inspect.py", line 482, in getmodule
    file = getabsfile(object, _filename)
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/inspect.py", line 466, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/Users/dwake/anaconda3/envs/Py27/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 24] Too many open files

---------------------------------------------------------------------------
IndexError
                                Traceback (most recent call last)

/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_code(self, code_obj, result)
   2897             if result is not None:
   2898                 result.error_in_exec = sys.exc_info()[1]
-> 2899             self.showtraceback()
   2900         else:
   2901             outflag = 0



/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in showtraceback(self, exc_tuple, filename, tb_offset, exception_only)
   1824                     except Exception:
   1825
                         stb = self.InteractiveTB.structured_traceback(etype,

-> 1826
                                             value, tb, tb_offset=tb_offset)

   1827
 

   1828                     self._showtraceback(etype, value, stb)



/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1410         self.tb =
 tb

   1411
         return FormattedTB.structured_traceback(

-> 1412
             self, etype, value, tb, tb_offset, number_of_lines_of_context)

   1413
 

   1414
 


/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1318             # Verbose modes need a full traceback
   1319
             return VerboseTB.structured_traceback(

-> 1320                 self, etype, value, tb, tb_offset,
 number_of_lines_of_context

   1321
             )

   1322         else:



/Users/dwake/anaconda3/envs/Py27/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1202                 structured_traceback_parts +=
 formatted_exception

   1203         else:
-> 1204             structured_traceback_parts += formatted_exception[0]
   1205
 

   1206         return
 structured_traceback_parts


IndexError
: string index out of range
```

**Comment by havok2063** [comment]
I think this is fixed with #681
