### ISSUE TITLE
cannot have access to 'VOR10' in MPL-6 & sometimes timeout / cannot get flux in remote mode & PyCharm

### ISSUE THREAD

**Issue by YiqingLiu** [sdss/marvin#415]
I am trying to analyse all data in MPL-6 in remote mode, and come across the 4 problems below: 

1.   I cannot have access to the DAP maps in the bintype of 'VOR10': 
>>> Maps(mangaid='1-321962', mode='remote',bintype='VOR10')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/maps.py", line 370, in _load_maps_from_api
    response = self._toolInteraction(url_full)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/core/core.py", line 349, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 51, in __init__
    self._sendRequest(request_type)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 280, in _sendRequest
    self._checkResponse(self._response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 245, in _checkResponse
    raise BrainError('Something went wrong on the server side: {0}'.format(errorMsg))
brain.core.exceptions.BrainError: Something went wrong on the server side: Failed to retrieve maps 8552-6101: Specified bintype VOR10 is not available in the DB.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/spaxel.py", line 72, in spaxel_factory
    return type.__call__(cls, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/maps.py", line 112, in __init__
    self._load_maps_from_api()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/maps.py", line 373, in _load_maps_from_api
    'found a problem when checking if remote maps exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote maps exists: Something went wrong on the server side: Failed to retrieve maps 8552-6101: Specified bintype VOR10 is not available in the DB.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

2.   I tried the commands below on two days: 
>>> DRPcube = Cube(mangaid='1-321962', mode='remote')
>>> flux = DRPcube.flux.value
The only difference is that the 'DRPcube' I use today was 'cc' yesterday. (Only the name changed.)  The first line works successfully on both days.  However, while the command of 'ccFlx = cc.flux.value' works well on both days, the 'flux = DRPcube.flux.value' I tried today could never give output.  (It finally finished just now, after over 1hr.)

3.   When I tied to run my 'pipeline', I got a long error report below.  Could you help to check what are the reasons for that?
python3 VbinSP.py
[WARNING]: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
INFO: No release version set. Setting default to MPL-6
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 331, in _error_catcher
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 413, in read
    data = self._fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 749, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 336, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 264, in _sendRequest
    headers=self.headers, stream=self.stream)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/raven/breadcrumbs.py", line 326, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 662, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 827, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 756, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/cube.py", line 411, in _get_extension_data
    params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/core/core.py", line 349, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 51, in __init__
    self._sendRequest(request_type)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 274, in _sendRequest
    raise BrainError('Requests Connection Error: {0}'.format(con))
brain.core.exceptions.BrainError: Requests Connection Error: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VbinSP.py", line 398, in <module>
    sn0_tab = SNcal(DRPcube_i, zz[i_gal], DAPmapCube_i)
  File "VbinSP.py", line 37, in SNcal
    flux = DRPcube.flux.value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/cube.py", line 307, in flux
    self._flux = self._get_datacube('flux')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/cube.py", line 274, in _get_datacube
    ivar=self._get_extension_data(name, 'ivar'),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marvin/tools/cube.py", line 414, in _get_extension_data
    'exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote cube exists: Requests Connection Error: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

4.   When I ran the codes in PyCharm, I met the error reports below.  Should I update anything? 
DRPcube_i = Cube(mangaid='1-321962',mode='remote')
[WARNING]: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
shape(DRPcube_i.flux)
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 293, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 293, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 293, in recv_into
    return self.recv_into(*args, **kwargs)
  [Previous line repeated 1 more times]
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 291, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/models.py", line 738, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 264, in _sendRequest
    headers=self.headers, stream=self.stream)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/raven/breadcrumbs.py", line 303, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/sessions.py", line 672, in send
    r.content
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/models.py", line 816, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/models.py", line 745, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/cube.py", line 411, in _get_extension_data
    params=params)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/core/core.py", line 349, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 51, in __init__
    self._sendRequest(request_type)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 274, in _sendRequest
    raise BrainError('Requests Connection Error: {0}'.format(con))
brain.core.exceptions.BrainError: Requests Connection Error: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-3c726d3c61d5>", line 1, in <module>
    shape(DRPcube_i.flux)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/cube.py", line 307, in flux
    self._flux = self._get_datacube('flux')
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/cube.py", line 266, in _get_datacube
    cube_data = self._get_extension_data(name)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/cube.py", line 414, in _get_extension_data
    'exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote cube exists: Requests Connection Error: HTTPSConnectionPool(host='api.sdss.org', port=443): Read timed out..
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

**Comment by albireox** [comment]
Hi @YiqingLiu,

Thanks for reporting these problems. Some answers to your problems:

1. For MPL-6 we decided against loading the VOR10 bintype to the database, so it cannot be accessed remotely (you can still open it from the FITS file if you download it). Instead, do `Maps(mangaid='1-321962', mode='remote',bintype='HYB10')` and that will give you the hybrid binning bintype, which is recommended for most uses. You may want to read the documentation for MPL-6 or talk to Kyle Westfall about whether HYB10 is appropriate for your science.

2. `flux = DRPcube.flux.value` can be a very slow command because you are requesting a whole datacube to be transmitted over the API. Whether it works or not may depend on your internet connection. In general, if you are going to be accessing the whole datacube, I recommend that you download the cube, so that Marvin can access it locally. You can have a look at the documentation [here](http://sdss-marvin.readthedocs.io/en/stable/core/downloads.html).

3. It's difficult to know what's happening from that error message but the timeout error indicates that probably Marvin is timing out at some point. It depends on what your pipeline is doing, but again, you may need to download the data before. That should be simple and you don't need to change your code, just make sure that Marvin is grabbing the data locally.

4. Unfortunately I don't use PyCharm and have no idea what the problem could be. If the same code works when you are not using PyCharm then there must be a problem with it. Maybe you can open an issue with the PyCharm team.

**Comment by YiqingLiu** [comment]
Thanks very much for the response, Jose.

>
>    1.
>
>    For MPL-6 we decided against loading the VOR10 bintype to the
>    database, so it cannot be accessed remotely (you can still open it from the
>    FITS file if you download it). Instead, do Maps(mangaid='1-321962',
>    mode='remote',bintype='HYB10') and that will give you the hybrid
>    binning bintype, which is recommended for most uses. You may want to read
>    the documentation for MPL-6 or talk to Kyle Westfall about whether HYB10 is
>    appropriate for your science.
>
> I tried the 'HYB10' in remote mode, but still failed to have access to.

>
>    1.
>
>    flux = DRPcube.flux.value can be a very slow command because you are
>    requesting a whole datacube to be transmitted over the API. Whether it
>    works or not may depend on your internet connection. In general, if you are
>    going to be accessing the whole datacube, I recommend that you download the
>    cube, so that Marvin can access it locally. You can have a look at the
>    documentation here
>    <http://sdss-marvin.readthedocs.io/en/stable/core/downloads.html>.
>
> It is indeed very slow, even if the network seems no problem.

>
>    1.
>
>    It's difficult to know what's happening from that error message but
>    the timeout error indicates that probably Marvin is timing out at some
>    point. It depends on what your pipeline is doing, but again, you may need
>    to download the data before. That should be simple and you don't need to
>    change your code, just make sure that Marvin is grabbing the data locally.
>
>
>    1.
>
>    Unfortunately I don't use PyCharm and have no idea what the problem
>    could be. If the same code works when you are not using PyCharm then there
>    must be a problem with it. Maybe you can open an issue with the PyCharm
>    team.
>
> I didn't meet these problems again. I am not sure what was wrong at that
moment.

**Comment by albireox** [comment]
Can you past here the error that you get when you try `Maps(mangaid='1-321962', mode='remote',bintype='HYB10')`? I just tried it in my computer and works fine.

**Comment by YiqingLiu** [comment]
Thanks, Jose.  I just tried it and found it worked.

Yiqing

2018-06-26 22:33 GMT+01:00 José Sánchez-Gallego <notifications@github.com>:

**Comment by albireox** [comment]
Great! Glad it worked. I'll close this issue but feel free to reopen it if or create a new one if you have other questions.
