### ISSUE TITLE
extract spaxels with a certain mask

### ISSUE THREAD

**Issue by YiqingLiu** [sdss/marvin#505]
I hope to extract the index number of DRP cubes where have a certain mask label. 
DRPcube.pixmask.labels can give me a list of what masks each spaxel has. 
However if I hope to know which spaxels have a certain mask e.g., 'DONOTUSE', how can I get the index number of these spaxels? 
Is there any commands like cube.getSpaxel(), which allow me to provide a mask label and return the spaxels with it?

**Comment by albireox** [comment]
Hi @YiqingLiu,

Yes, what you want to do is possible with Marvin. The first step is to get the spaxels that contain a certain set of pixmask labels. To do that you can use the `pixmask` attribute in the Tools, with the `get_mask` method. For instance, say that you want to get the elements of a cube that contain `DONOTUSE`

```python
cube = Cube('8485-1901')
donotuse = cube.pixmask.get_mask('DONOTUSE')
```

You'll note that's a 3D array in which the values marked as `DONOTUSE` have a value > 0. If you want, you can pass `get_mask` a list of labels, and the values > 0 will be the ones that match all the labels. Now we need to get a list of the `(x, y)` coordinates of the spaxels that contain at least one wavelength element with the maskbit set to `DONOTUSE`.  We can do that as

```python
w, y, x = numpy.where(donotuse > 0)
```
And now we need to get the spaxels for each `(x, y)` pair as

```python
spaxel = cube.getSpaxel(x=x, y=y, xyorig='lower')
```

Check how many spaxels this is going to return because it may be a lot of them and the command can be quite slow. You may want to retrieve the spaxels in smaller batches.

Have a look at the documentation for `Maskbit` [here](http://sdss-marvin.readthedocs.io/en/stable/utils/maskbit.html).

Also note that this will change slightly with the next release of Marvin, but the documentation will change accordingly. Let me know if this does not work for you.

**Comment by YiqingLiu** [comment]
Thanks, @albireox . 

- I followed your instruction and found that it doesn't work if I give a mask name which is not labeled for any spaxels in the cube. For example: 

```
skybad = cb.pixmask.get_mask('SKYSUBBAD')
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-21209c7e18e5>", line 1, in <module>
    skybad = cb.pixmask.get_mask('SKYSUBBAD')
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/utils/general/maskbit.py", line 376, in get_mask
    bits = self.labels_to_bits(labels)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/utils/general/maskbit.py", line 339, in labels_to_bits
    return self.values_to_bits(self.labels_to_value(labels))
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/utils/general/maskbit.py", line 317, in labels_to_value
    bit_values = [self.schema.bit[self.schema.label == label].values[0] for label in labels]
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/utils/general/maskbit.py", line 317, in <listcomp>
    bit_values = [self.schema.bit[self.schema.label == label].values[0] for label in labels]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
- Even if for the existed masks like 'DONOTUSE', I cannot get the spaxels successfully. 
```
spaxel = cb.getSpaxel(x=x, y=y, xyorig='lower')
[WARNING]: MarvinUserWarning: local mode failed. Trying remote now.
[WARNING]: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.85', 52913), raddr=('155.101.19.80', 443)>
[WARNING]: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.85', 52962), raddr=('155.101.19.80', 443)>
[WARNING]: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.85', 53011), raddr=('155.101.19.80', 443)>
[WARNING]: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.85', 53058), raddr=('155.101.19.80', 443)>
[WARNING]: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.85', 53106), raddr=('155.101.19.80', 443)>
[WARNING]: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.85', 53152), raddr=('155.101.19.80', 443)>
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 198, in _checkResponse
    isbad = response.raise_for_status()
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: TOO MANY REQUESTS for url: https://api.sdss.org/marvin2/api/maps/9044-1901/SPX/GAU-MILESHC/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/maps.py", line 370, in _load_maps_from_api
    response = self._toolInteraction(url_full)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/core/core.py", line 349, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 51, in __init__
    self._sendRequest(request_type)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 280, in _sendRequest
    self._checkResponse(self._response)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 221, in _checkResponse
    raise BrainError('Requests Http Status Error: {0}\n{1}'.format(http, errmsg))
brain.core.exceptions.BrainError: Requests Http Status Error: 429 Client Error: TOO MANY REQUESTS for url: https://api.sdss.org/marvin2/api/maps/9044-1901/SPX/GAU-MILESHC/
200 per 1 minute
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    class, or ``None`` if a suitable handler is not found.
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1831, in preprocess_request
    response = self.make_response(rv)
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-f9dd7d46ca2f>", line 1, in <module>
    spaxel = cb.getSpaxel(x=x, y=y, xyorig='lower')
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/cube.py", line 613, in getSpaxel
    modelcube=models, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/utils/general/general.py", line 191, in getSpaxel
    **kwargs))
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/spaxel.py", line 110, in spaxel_factory
    release=release, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/spaxel.py", line 72, in spaxel_factory
    return type.__call__(cls, *args, **kwargs)
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/maps.py", line 112, in __init__
    self._load_maps_from_api()
  File "/Users/yiqingliu/anaconda/envs/py36/lib/python3.6/site-packages/marvin/tools/maps.py", line 373, in _load_maps_from_api
    'found a problem when checking if remote maps exists: {0}'.format(str(ee)))
marvin.core.exceptions.MarvinError: found a problem when checking if remote maps exists: Requests Http Status Error: 429 Client Error: TOO MANY REQUESTS for url: https://api.sdss.org/marvin2/api/maps/9044-1901/SPX/GAU-MILESHC/
200 per 1 minute
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    class, or ``None`` if a suitable handler is not found.
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask/app.py", line 1831, in preprocess_request
    response = self.make_response(rv)
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 465, in __check_request_limit
    six.reraise(*sys.exc_info())
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/flask_limiter/extension.py", line 359, in __evaluate_limits
    raise RateLimitExceeded(exc_description)
.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.
```
I never used remote mode in my program. The cb is read from a cube in my local directory. 
Could you please help?

**Comment by albireox** [comment]
Hi @YiqingLiu,

The bit mask label you are trying to use, `SKYSUBBAD` is a `MANGA_DRP3QUAL` one, which is the quality flag that applies to the whole cube. You can access that if you want by doing `cb.quality_flag`. The `pixmask` refers to the `MANGA_DRP3PIXMASK` flag, which does not contain a `SKYSUBBAD` label. That said, the error message should be more obvious, but it is not a bug.

For your second problem, do you have also the MAPS file associated with that plateifu? When you load a spaniel from `Cube`, the MAPS properties are also loaded. If you don't have the file then Marvin will fall back to remote. You can disable that by calling `cb.getSpaxel(x=x, y=y, xyorig='lower', properties=False)`, which will only load the Cube quantities for that spaxel (flux, ivar, mask, dispersion, etc.)
