### ISSUE TITLE
importing marvin gives a matplotlib backend error

### ISSUE THREAD

**Issue by havok2063** [sdss/marvin#564]
**Describe the bug**
After installing `marvin`, trying to import marvin gives a `matplotlib` backend error

**To Reproduce**
```
from marvin import config

INFO: No release version set. Setting default to DR15
/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/__init__.py:364: MarvinUserWarning: path /Users/dlaw/MANGApipe/spectro/redux/v2_4_3/drpall-v2_4_3.fits cannot be found. Setting drpall to None.
  .format(value), MarvinUserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/__init__.py", line 726, in <module>
    from marvin.api.api import Interaction
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/api/__init__.py", line 15, in <module>
    from marvin.utils.datamodel.dap import datamodel as dm
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/utils/datamodel/dap/__init__.py", line 2, in <module>
    from .base import *
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/utils/datamodel/dap/base.py", line 23, in <module>
    from marvin.utils.general.structs import FuzzyList, get_best_fuzzy
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/utils/general/__init__.py", line 2, in <module>
    from marvin.utils.general.general import *
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/marvin/utils/general/general.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/dlaw/anaconda3/envs/marvindev/lib/python3.5/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

**Expected behavior**
A clean import.

**Comment by havok2063** [comment]
This problem has been documented here.  https://sdss-marvin.readthedocs.io/en/latest/installation.html#matplotlib-backend-problems
