### ISSUE TITLE
cannot find Maps file for plateifu='8312-6101'

### ISSUE THREAD

**Issue by bbemc2** [sdss/marvin#701]
**Describe the bug**
cannot retrieve Maps file for plateifu='8312-6101'

Traceback (most recent call last):

```
  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/maps.py", line 379, in _load_maps_from_api
    response = self._toolInteraction(url_full)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/core.py", line 132, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 56, in __init__
    self._sendRequest(request_type)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 294, in _sendRequest
    self._checkResponse(self._response)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 258, in _checkResponse
    raise BrainError('Something went wrong on the server side: {0}'.format(errorMsg))

BrainError: Something went wrong on the server side: Failed to retrieve maps 8312-6101: no Maps file found for this combination of parameters.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/path/plt.py", line 18, in <module>
    maps = Maps(plateifu='8312-6101')

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/maps.py", line 113, in __init__
    self._load_maps_from_api()

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/maps.py", line 382, in _load_maps_from_api
    'found a problem when checking if remote maps exists: {0}'.format(str(ee)))

MarvinError: found a problem when checking if remote maps exists: Something went wrong on the server side: Failed to retrieve maps 8312-6101: no Maps file found for this combination of parameters.Traceback (most recent call last):

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/maps.py", line 379, in _load_maps_from_api
    response = self._toolInteraction(url_full)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/core.py", line 132, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 56, in __init__
    self._sendRequest(request_type)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 294, in _sendRequest
    self._checkResponse(self._response)

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/extern/marvin_brain/python/brain/api/api.py", line 258, in _checkResponse
    raise BrainError('Something went wrong on the server side: {0}'.format(errorMsg))

BrainError: Something went wrong on the server side: Failed to retrieve maps 8312-6101: no Maps file found for this combination of parameters.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/plt.py", line 18, in <module>
    maps = Maps(plateifu='8312-6101')

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/maps.py", line 113, in __init__
    self._load_maps_from_api()

  File "/opt/anaconda3/envs/sdss/lib/python3.7/site-packages/marvin/tools/maps.py", line 382, in _load_maps_from_api
    'found a problem when checking if remote maps exists: {0}'.format(str(ee)))

MarvinError: found a problem when checking if remote maps exists: Something went wrong on the server side: Failed to retrieve maps 8312-6101: no Maps file found for this combination of parameters.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. maps = Maps(plateifu='8312-6101')
2. image = Image(plateifu='8312-6101')
image.plot()

**Expected behaviour**
I should be able to connect the maps file and make some plots.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Version of Marvin: 2.3.5

**Additional context**

**Comment by havok2063** [comment]
@bbemc2 This plate-ifu is not a real galaxy.  It's a FILLER galaxy with a "Do Not Use" quality flags set for the Cube.  So it was never processed through the Data Analysis Pipeline to produce MAPS files.   See https://dr16.sdss.org/marvin/galaxy/8312-6101/
