### ISSUE TITLE
cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by Surendra-Bhattarai** [sdss/marvin#800]
Hi. I am trying to install sdss-marvin in my Ubuntu system. But it is showing me the following error:

[ERROR]: Traceback (most recent call last):
File "/home/krittika/.local/bin/run_marvin", line 20, in
from marvin.web import create_app
File "/home/krittika/.local/lib/python3.10/site-packages/marvin/init.py", line 29, in
from brain.utils.general.general import getDbMachine
File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/init.py", line 2, in
from brain.utils.general.general import *
File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/general.py", line 12, in
from flask import url_for
File "/home/krittika/.local/lib/python3.10/site-packages/flask/init.py", line 14, in
from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/dist-packages/jinja2/init.py)

I have tried all the debugging steps suggested in previous query https://github.com/sdss/marvin/issues/791 by someone. I also downgraded the jinja2, but this did not help.

**Comment by Surendra-Bhattarai** [comment]
Hi. I am trying to install sdss-marvin in my Ubuntu system. But it is showing me the following error:

[ERROR]: Traceback (most recent call last):
  File "/home/krittika/.local/bin/run_marvin", line 20, in <module>
    from marvin.web import create_app
  File "/home/krittika/.local/lib/python3.10/site-packages/marvin/__init__.py", line 29, in <module>
    from brain.utils.general.general import getDbMachine
  File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/__init__.py", line 2, in <module>
    from brain.utils.general.general import *
  File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/general.py", line 12, in <module>
    from flask import url_for
  File "/home/krittika/.local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/dist-packages/jinja2/__init__.py)

I have tried all the debugging steps suggested in previous query #791 by someone. I also downgraded the jinja2, but this did not help.

**Comment by Surendra-Bhattarai** [comment]
Also, after doing some version changes, when I am checking whether marvin is installed properly or not, I am getting this error:

System Checks
Your Python Version: 3.10.12
Full Version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

OS Checks
Platform: linux
Full info: posix.uname_result(sysname='Linux', nodename='krittika-supermicro', release='5.19.0-41-generic', version='#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2', machine='x86_64')

Distribution Checks
Is Python from Anaconda or Miniconda? False

Package Checks
libEGL warning: DRI3: failed to query the version
libEGL warning: DRI2: failed to authenticate
Numpy version: 1.24.3
Matplotlib version: 3.7.1
Your Matplotlib backend is GTK4Agg

Netrc Checks
Have a .netrc file? True
Netrc with permissions 600? True

Marvin Checks
[ERROR]: Traceback (most recent call last):
  File "/home/krittika/.local/bin/check_marvin", line 63, in <module>
    import marvin
  File "/home/krittika/.local/lib/python3.10/site-packages/marvin/__init__.py", line 29, in <module>
    from brain.utils.general.general import getDbMachine
  File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/__init__.py", line 2, in <module>
    from brain.utils.general.general import *
  File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/general.py", line 12, in <module>
    from flask import url_for
ModuleNotFoundError: No module named 'flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krittika/.local/bin/check_marvin", line 66, in <module>
    raise ImportError('Marvin cannot be imported! {0}\n{1}'.format(e, traceback))
**ImportError: Marvin cannot be imported! No module named 'flask'**
<traceback object at 0x7f27705ee200>

**Comment by havok2063** [comment]
Hi @Surendra-Bhattarai The `jinja2` error is an issue with the dependency chain of marvin.  Please see https://github.com/sdss/marvin/issues/791, https://github.com/sdss/marvin/issues/793.  In the future, please check all open and closed issues to see if your problem has already been reported.

**Comment by Surendra-Bhattarai** [comment]
I had checked those issues (#791, #793). But even after following your suggestion on #793, I got the following error when I did **check_marvin**:

_/home/krittika/anaconda3/envs/marvin/bin/check_marvin:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('sdss-marvin==2.8.1.dev0')

System Checks
Your Python Version: 3.10.12
Full Version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]

OS Checks
Platform: linux
Full info: posix.uname_result(sysname='Linux', nodename='krittika-supermicro', release='5.19.0-41-generic', version='#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2', machine='x86_64')

Distribution Checks
Is Python from Anaconda or Miniconda? False

Package Checks
Numpy version: 1.24.3
Matplotlib version: 3.7.1
Your Matplotlib backend is agg

Netrc Checks
Have a .netrc file? True
Netrc with permissions 600? True

Marvin Checks
Traceback (most recent call last):
  File "/home/krittika/anaconda3/envs/marvin/bin/check_marvin", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/krittika/Surendra/marvin/bin/check_marvin", line 68, in <module>
    marvinmode = marvin.config.mode is not None
AttributeError: **module 'marvin' has no attribute 'config'**_

**Comment by Surendra-Bhattarai** [comment]
And   **from marvin import config** gave the following error:

_```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: **cannot import name 'config' from 'marvin'** (/home/krittika/anaconda3/envs/marvin/lib/python3.10/site-packages/marvin/__init__.py)
```_

Hence, after getting all these error, I decided to raise this issue.

**Comment by havok2063** [comment]
It seems like something is wonky with your installation.  I would try a clean install of marvin in a fresh conda environment, and then follow #791.

**Comment by Surendra-Bhattarai** [comment]
Did you get any error with your new installation? 

I also started with a clean environment, and followed the exact steps, but still got error in ```pip install -e ".[dev,web,db]"```.

I even tried with different version of python (3.10), but got this error:

``` ERROR: Exception:
Traceback (most recent call last):
  File "/home/krittika/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/krittika/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/krittika/.local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/krittika/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/krittika/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/krittika/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

Do let me know if there has been an update/upgrade in marvin which may be causing this issue.

**Comment by Surendra-Bhattarai** [comment]
You can also see the output of ```check_marvin``` here:

```System Checks
Your Python Version: 3.10.12
Full Version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

OS Checks
Platform: linux
Full info: posix.uname_result(sysname='Linux', nodename='krittika-supermicro', release='5.19.0-41-generic', version='#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2', machine='x86_64')

Distribution Checks
Is Python from Anaconda or Miniconda? False

Package Checks
Numpy version: 1.24.3
Matplotlib version: 3.7.1
Your Matplotlib backend is agg

Netrc Checks
Have a .netrc file? True
Netrc with permissions 600? True

Marvin Checks
[ERROR]: Traceback (most recent call last):
  File "/home/krittika/Surendra/marvin/bin/check_marvin", line 63, in <module>
    import marvin
  File "/home/krittika/Surendra/marvin/python/marvin/__init__.py", line 29, in <module>
    from brain.utils.general.general import getDbMachine
  File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/__init__.py", line 2, in <module>
    from brain.utils.general.general import *
  File "/home/krittika/.local/lib/python3.10/site-packages/brain/utils/general/general.py", line 12, in <module>
    from flask import url_for
  File "/usr/local/lib/python3.10/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/dist-packages/jinja2/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krittika/.local/bin/check_marvin", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/krittika/Surendra/marvin/bin/check_marvin", line 66, in <module>
    raise ImportError('Marvin cannot be imported! {0}\n{1}'.format(e, traceback))
ImportError: Marvin cannot be imported! cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/dist-packages/jinja2/__init__.py)
<traceback object at 0x7f0db26f9540>```

**Comment by havok2063** [comment]
@Surendra-Bhattarai After a fresh install of marvin, you need to downgrade the `jinja2` package with `pip install -U "jinja2>3,<3.1"`, following https://github.com/sdss/marvin/issues/791. You need a version of `jinja2 < 3.1`.

**Comment by Surendra-Bhattarai** [comment]
This also did not work.

I, however, am now able to resolve the issue. I installed the package ```jinja2``` and all other relevant packages in the same directory where ```__init__.py``` file was located. I did not understand why this silly thing resolved it, but yaa it works. And if anyone is having a similar issue, they may try this approach.

Thanks Brian for all the help.
