### ISSUE TITLE
Issues with Marvin after ~6 months not using

### ISSUE THREAD

**Issue by RickJones4416** [sdss/marvin#816]
I was using Marvin from anaconda/miniconda about 6 months ago without issues. Now, when I try and use Cubes or Maps, I get the error that I posted below. I ran a basic cube import and print(cube) to test a simple line of code. I also posted the response to check_marvin on my OS terminal below the error:

[ERROR]: Traceback (most recent call last):
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/brain/api/api.py", line 201, in _checkResponse
    isbad = response.raise_for_status()
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: CONFLICT for url: https://magrathea.sdss.org/marvin/api/cubes/8148-9102/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/marvin/tools/cube.py", line 240, in _load_cube_from_api
    response = self._toolInteraction(url.format(name=self.plateifu))
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/marvin/tools/core.py", line 134, in _toolInteraction
    return marvin.api.api.Interaction(url, params=params)
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/brain/api/api.py", line 57, in __init__
    self._sendRequest(request_type)
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/brain/api/api.py", line 302, in _sendRequest
    self._checkResponse(self._response)
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/brain/api/api.py", line 242, in _checkResponse
    raise BrainError('Requests Http Status Error: {0}\n{1}'.format(http, errmsg))
brain.core.exceptions.BrainError: Requests Http Status Error: 409 Client Error: CONFLICT for url: https://magrathea.sdss.org/marvin/api/cubes/8148-9102/
Error: data release None no longer supported by the Marvin API. Update to a later MPL or use Marvin's local file access mode instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/y0/3l2gq7lj6pn83cs9wf47tf4h0000gn/T/ipykernel_1083/1136808075.py", line 5, in <module>
    galaxy = Cube(plateifu='8148-9102')
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/marvin/tools/cube.py", line 78, in __init__
    self._load_cube_from_api()
  File "/Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/marvin/tools/cube.py", line 242, in _load_cube_from_api
    raise MarvinError('found a problem when checking if remote cube '
marvin.core.exceptions.MarvinError: found a problem when checking if remote cube exists: Requests Http Status Error: 409 Client Error: CONFLICT for url: https://magrathea.sdss.org/marvin/api/cubes/8148-9102/
Error: data release None no longer supported by the Marvin API. Update to a later MPL or use Marvin's local file access mode instead.
You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).
Fill out a subject and some text describing the error that just occurred.
If able, copy and paste the full traceback information into the issue as well.

Results of check_marvin:

System Checks
Your Python Version: 3.8.18
Full Version: 3.8.18 (default, Sep 11 2023, 08:17:16) 
[Clang 14.0.6 ]

OS Checks
Platform: darwin
Full info: posix.uname_result(sysname='Darwin', nodename='Richards-MBP.attlocal.net', release='23.5.0', version='Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020', machine='arm64')

Distribution Checks
Is Python from Anaconda or Miniconda? False

Package Checks
Numpy version: 1.24.3
Matplotlib version: 3.7.2
Your Matplotlib backend is MacOSX

Netrc Checks
Have a .netrc file? False

Marvin Checks
[INFO]: No release version set. Setting default to DR17
[WARNING]: path /Users/richardjones/sas/dr17/manga/spectro/redux/v3_1_1/drpall-v3_1_1.fits cannot be found. Setting drpall to None. (MarvinUserWarning)
[WARNING]: path /Users/richardjones/sas/dr17/manga/spectro/analysis/v3_1_1/3.1.0/dapall-v3_1_1-3.1.0.fits cannot be found. Setting dapall to None. (MarvinUserWarning)
Marvin imported? True
Marvin version: 2.8.0
Does Marvin have a URLMap for API use? True
Has a db? False

Marvin Paths:
$SAS_BASE_DIR:  /Users/richardjones/sas
$MANGA_SPECTRO_REDUX:  /Users/richardjones/sas/dr17/manga/spectro/redux
$MANGA_SPECTRO_ANALYSIS:  /Users/richardjones/sas/dr17/manga/spectro/analysis
$TREE_DIR:  /Users/richardjones/anaconda3/envs/marvin/lib/python3.8/site-packages/tree
$MARVIN_BRAIN_DIR:  None
$SDSS_ACCESS_DIR:  None
DRPall Path:  None

**Comment by bretthandrews** [comment]
This should fix the problem for the mean time until @havok2063 can release a new version: https://github.com/sdss/marvin/issues/810#issuecomment-2176729494

**Comment by rjsmethurst** [comment]
Thanks Brett - that workaround worked for me as well!

**Comment by bretthandrews** [comment]
No problem!
