### ISSUE TITLE
URL Connection Prbs using Marvin

### ISSUE THREAD

**Issue by hplana** [sdss/marvin#820]
**Describe the bug**
I have several prbs installing Marvin on Ubuntu. When doing import marvin in python, I have series of errors mentioning an outdated matplotlib, when is the current v3.3.4 version.

I then try to import a map following oen of the example:
>>> import copy
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from marvin.tools.maps import Maps
>>> maps = Maps(plateifu='8711-6102')

Then I have a warning +  error:

[WARNING]: Cannot retrieve URLMap. Remote functionality will not work: Requests Connection Error: HTTPSConnectionPool(host='dr17.sdss.org', port=443): Max retries exceeded with url: /marvin/api/general/getroutemap?release=DR17&compression=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74034b54a8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (MarvinUserWarning)
[ERROR]: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda3/lib/python3.6/site-packages/marvin/tools/maps.py", line 113, in __init__
    self._load_maps_from_api()
  File "~/anaconda3/lib/python3.6/site-packages/marvin/tools/maps.py", line 372, in _load_maps_from_api
    url = marvin.config.urlmap['api']['getMaps']['url']
  File "~/anaconda3/lib/python3.6/site-packages/brain/core/core.py", line 37, in __missing__
    raise BrainError('No URL Map found. Cannot make remote call')
brain.core.exceptions.BrainError: No URL Map found. Cannot make remote call

I quite do not understand if the prb is coming from the installation or from a connection error.

I hope you can help me 
Thanks a lot

My system is Ubuntu 16.04 and marvin is the last version available on the web site.

**Comment by havok2063** [comment]
Can you try updating to 2.8.1 and see if you get the same error?
