### ISSUE TITLE
Cannot load Image object due to invalid drpall version

### ISSUE THREAD

**Issue by bp572** [sdss/marvin#821]
**Describe the bug**
I am trying to load an Image object, however, I am getting an error regarding invalid drpall version. This worked for me a year ago but it stopped working now. I am able to load Maps but not Image. I have the Image I am looking for downloaded, however I need to plot something on top of it for which I need the wcs of that image object. So I need to be able to get image object for my purpose. I have tried switching the DR version to DR15 and DR16, but same issue.

**Code**
import marvin
from marvin import config
config.setDR('DR17')
config.switchSasUrl(sasmode='mirror')
from marvin.tools.cube import Cube
from marvin.tools.maps import Maps
from marvin.tools.image import Image
maps = Maps(plateifu='7960-12704') 
image = Image(plateifu='7960-12704')

**Desktop:**
 - OS: MacOS
 - Language - python
 - Version - sdss-marvin 2.8.0

**Error**
[ERROR]: Traceback (most recent call last):
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/54/jl53s_6x6wg6431pqzl_3dw80000gn/T/ipykernel_95317/805156777.py", line 1, in <module>
    Image(plateifu=fast[i])
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/tools/image.py", line 77, in __init__
    self._load_image_from_api()
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/tools/image.py", line 172, in _load_image_from_api
    filepath = self._getFullPath()
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/tools/image.py", line 134, in _getFullPath
    dir3d = self._get_image_dir()
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/tools/image.py", line 123, in _get_image_dir
    is_mastar = target_is_mastar(self.plateifu, drpver=self._drpver)
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/utils/general/general.py", line 1731, in target_is_mastar
    row = get_drpall_row(plateifu, drpver=drpver, drpall=drpall)
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/utils/general/general.py", line 989, in get_drpall_row
    drpall_table = get_drpall_table(drpver=drpver, drpall=drpall, hdu='MANGA')
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/utils/general/general.py", line 1771, in get_drpall_table
    hduext = hdu if check_versions(drpver, 'v2_5_3') else 'MANGA'
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/marvin/utils/general/general.py", line 1861, in check_versions
    return parse(version1) >= parse(version2)
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/packaging/version.py", line 56, in parse
    return Version(version)
  File "/opt/anaconda3/envs/psb_project/lib/python3.8/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v3_1_1'

**Comment by astronom4ek** [comment]
I have the same problem. Although the  trick '(sasmode='mirror')' worked a week ago.

**Comment by bretthandrews** [comment]
Please give this a try: https://github.com/sdss/marvin/issues/810#issuecomment-2176729494
