### ISSUE TITLE
sdss-tree issue

### ISSUE THREAD

**Issue by hplana** [sdss/marvin#822]
Hi. I am trying to use the DRPall table. By doing the following command:
data = get_drpall_table(), I got a serie of errors.
>>> data = get_drpall_table()
[ERROR]: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/plana/anaconda3/lib/python3.6/site-packages/marvin/utils/general/general.py", line 1756, in get_drpall_table
    get_drpall_file(drpall=drpall, drpver=drpver)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/marvin/utils/general/general.py", line 963, in get_drpall_file
    _get_summary_file('drpall', summary_path=drpall, drpver=drpver)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/marvin/utils/general/general.py", line 931, in _get_summary_file
    summary_path = get_drpall_path(drpver)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/marvin/utils/general/general.py", line 1428, in get_drpall_path
    drpall_path = _get_summary_path('drpall', drpver=drpver)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/marvin/utils/general/general.py", line 1420, in _get_summary_path
    path = Path(release=release)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/sdss_access/path/path.py", line 1157, in __init__
    force_modules=force_modules, preserve_envvars=preserve_envvars)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/sdss_access/path/path.py", line 124, in __init__
    self.public = check_public_release(release=self.release, public=public)
  File "/home/plana/anaconda3/lib/python3.6/site-packages/sdss_access/path/path.py", line 70, in check_public_release
    raise AttributeError("Cannot find a valid release date in the sdss-tree product.  Try upgrading to min. version 3.1.0.")
AttributeError: Cannot find a valid release date in the sdss-tree product.  Try upgrading to min. version 3.1.0.

I also encouter similar prbs when trying , the "downloadList(galaxies, dltype='maps')" procedure.
I try to install a new version (as mentioned), by doing pip install sdss-tree, or sdss-access or pip install --upgrade sdss-tree, but the system returns that "Requirement already satisfied".

I am using a desktop, with Ubuntu 16.04. The Marvin version is the one currently available on the web site.
Thanks a lot.
H. Plana

**Comment by havok2063** [comment]
Can you try updating to 2.8.1 and see if you get the same error?
