### ISSUE TITLE
Python fails to pip-install with Python 3

### ISSUE THREAD

**Issue by albireox** [sdss/marvin#86]
```
$ pip install sdss-marvin
Collecting sdss-marvin
  Using cached sdss-marvin-2.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cf/3z1t7yzj7q1828mvh3vdg5sh0000gp/T/pip-build-wsr3vyle/sdss-marvin/setup.py", line 41, in <module>
        install_requires = [line.strip().replace('==', '>=') for line in open(requirements_file)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/cf/3z1t7yzj7q1828mvh3vdg5sh0000gp/T/pip-build-wsr3vyle/sdss-marvin/requirements.txt'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cf/3z1t7yzj7q1828mvh3vdg5sh0000gp/T/pip-build-wsr3vyle/sdss-marvin/
```

This is probably due to some inconsistency between how Python 3 handles relative paths in `setup.py`.

**Comment by albireox** [comment]
This is now fixed and tested. Should work after we release a new version. The problem is that for Python 3 pip uses the source file + python setup.py, which requires both README.md and requirements.txt to be included in the tar file. I have added them to the list of non-python files that should be tarballed.
